services:
  twitter:
    container_name: twitter
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./twitter:/twitter
      - ./staticfiles:/staticfiles/
      - ./data/media:/data/media/
    env_file:
      - .env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - .env