# Generated by Django 5.1.2 on 2024-10-27 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 26, 21, 43, 18, 852430)),
        ),
    ]
