# Generated by Django 5.1.2 on 2024-10-27 19:20

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_profile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[api.validators.validate_image_size]),
        ),
    ]
